[package]
name = "riskmulator-studio"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [] }
riskmulator-simulation-engine = { path = "../../../crates/simulation-engine" }
riskmulator-studio-core = { path = "../../../crates/studio-core" }
serde = { version = "1.0", features = ["derive"] }
